services:
  dev:
    image: rails7-template-dev
    build:
      context: ..
      dockerfile: ./docker/dev/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    env_file:
      - ../docker/env
    volumes:
      - ..:/workspace
    depends_on:
      - db

  db:
    image: rails7-template-db
    build:
      context: ..
      dockerfile: ./docker/db/Dockerfile
    env_file:
      - ../docker/env
      - ../docker/db/env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
